ex = SyntaxError('not a chance'); ex.__traceback__ = None; raise ex
